# Generated by Django 3.2.8 on 2022-05-18 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=30)),
                ('description_text', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(height_field=500, upload_to='', width_field=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buset.posting')),
            ],
        ),
    ]
