# Generated by Django 3.2.8 on 2022-05-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='pub_date',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='description_text',
            new_name='post_description',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='price',
            new_name='post_price',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='title_text',
            new_name='post_title',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='posting',
            name='post_image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
